name: Waka Readme

on:
  schedule:
    - cron: '0 * * * *'  # 每小时更新一次
  workflow_dispatch:     # 手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
